/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import Controller.CProduct;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author USER
 */
public class Product1 extends javax.swing.JFrame {
CProduct product = new CProduct();
    /**
     * Creates new form Product1
     */
    public Product1() {
        initComponents();
        txt_pId.setEditable(false);
        txt_pId.setText(Integer.toString (product.getId()));
        tbl_product.setModel(DbUtils.resultSetToTableModel(product.populate()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_product = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btn_add = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        btn_dlt = new javax.swing.JButton();
        cmb_inventory = new javax.swing.JComboBox<>();
        txt_qty = new javax.swing.JTextField();
        txt_price = new javax.swing.JTextField();
        txt_discription = new javax.swing.JTextField();
        txt_pName = new javax.swing.JTextField();
        txt_pId = new javax.swing.JTextField();
        txt_home = new javax.swing.JButton();
        lbl_name2 = new javax.swing.JLabel();
        lbl_name4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1080, 580));
        setMinimumSize(new java.awt.Dimension(1080, 580));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1080, 580));
        setSize(new java.awt.Dimension(1080, 580));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_product.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_product.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_productMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_product);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 80, -1, -1));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Product Id ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, -1, -1));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Product Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Discription");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, -1, -1));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Price");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, -1));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Quantity");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, -1, -1));

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Inventory");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, -1, -1));

        btn_add.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btn_add.setText("Add");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });
        getContentPane().add(btn_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 70, 30));

        btn_edit.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btn_edit.setText("Edit");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });
        getContentPane().add(btn_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 80, -1));

        btn_clear.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });
        getContentPane().add(btn_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, 80, -1));

        btn_dlt.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btn_dlt.setText("Delete");
        btn_dlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dltActionPerformed(evt);
            }
        });
        getContentPane().add(btn_dlt, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, -1, 30));

        cmb_inventory.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cmb_inventory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laptop", "Desktop", "Phone", "Tab", "Tv" }));
        getContentPane().add(cmb_inventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 117, -1));

        txt_qty.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txt_qty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_qtyActionPerformed(evt);
            }
        });
        txt_qty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_qtyKeyPressed(evt);
            }
        });
        getContentPane().add(txt_qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 117, -1));

        txt_price.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txt_price.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_priceKeyPressed(evt);
            }
        });
        getContentPane().add(txt_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 117, -1));

        txt_discription.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        getContentPane().add(txt_discription, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 117, -1));

        txt_pName.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        getContentPane().add(txt_pName, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 117, -1));

        txt_pId.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        getContentPane().add(txt_pId, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 117, -1));

        txt_home.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txt_home.setText("Home");
        txt_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_homeActionPerformed(evt);
            }
        });
        getContentPane().add(txt_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 510, -1, 30));

        lbl_name2.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lbl_name2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_name2.setText("Product");
        getContentPane().add(lbl_name2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 50, 70, 28));

        lbl_name4.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        lbl_name4.setForeground(new java.awt.Color(255, 255, 255));
        lbl_name4.setText("Product Page");
        getContentPane().add(lbl_name4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 150, 40));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0,120));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/red-x-mark-transparent-background-3.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 990, Short.MAX_VALUE)
                .addComponent(jLabel8))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 501, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 1010, 530));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/pexels-pixabay-4158.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 580));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        int invent_id = 0;
        int userId = 0;
        
        String id = txt_pId.getText(); // Get the text from your input field
        if (!id.isEmpty()) {
            userId = Integer.parseInt(txt_pId.getText());
        }
        String pName = txt_pName.getText();
        String discription = txt_discription.getText();
        int price = 0;
        String prc = txt_price.getText(); // Get the text from your input field
        if (!prc.isEmpty()) {
            price = Integer.parseInt(txt_price.getText());
        }
        int quntity = 0;
        String qty = txt_qty.getText(); // Get the text from your input field
        if (!qty.isEmpty()) {
            quntity = Integer.parseInt(txt_qty.getText());
        }
        String int_id = cmb_inventory.getSelectedItem().toString();
        switch (int_id){
            case "Laptop" -> invent_id = 1;
            case "Desktop" -> invent_id = 2;
            case "Phone" -> invent_id = 3;
            case "Tab" -> invent_id = 4;
            case "Tv" -> invent_id = 5;
            default -> {
            }
        }
        
        product.add(pName,discription,price,quntity,invent_id);
        product.autoIncrement();
        txt_pId.setText(Integer.toString (product.getId()));
        tbl_product.setModel(DbUtils.resultSetToTableModel(product.populate()));
        
    }//GEN-LAST:event_btn_addActionPerformed
    
    void clear(){
        txt_discription.setText("");
        txt_pName.setText("");
        txt_price.setText("");
        txt_qty.setText(""); 
    }
    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
       clear(); // TODO add your handling code here:
    }//GEN-LAST:event_btn_clearActionPerformed

    private void txt_qtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_qtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_qtyActionPerformed

    private void txt_qtyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_qtyKeyPressed
        char c = evt.getKeyChar();
        if(Character.isLetter(c)){
            txt_qty.setEditable(false);
            JOptionPane.showMessageDialog(null, "Please enter numbers only", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            txt_qty.setEditable(true);
        }      // TODO add your handling code here:
    }//GEN-LAST:event_txt_qtyKeyPressed

    private void txt_priceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_priceKeyPressed
        char c = evt.getKeyChar();
        if(Character.isLetter(c)){
            txt_price.setEditable(false);
            JOptionPane.showMessageDialog(null, "Please enter numbers only", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            txt_price.setEditable(true);
        }                   // TODO add your handling code here:
    }//GEN-LAST:event_txt_priceKeyPressed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
         int invent_id = 0;
        int userId = 0;
        
        String id = txt_pId.getText(); // Get the text from your input field
        if (!id.isEmpty()) {
            userId = Integer.parseInt(txt_pId.getText());
        }
        String pName = txt_pName.getText();
        String discription = txt_discription.getText();
        int price = 0;
        String prc = txt_price.getText(); // Get the text from your input field
        if (!prc.isEmpty()) {
            price = Integer.parseInt(txt_price.getText());
        }
        int quntity = 0;
        String qty = txt_qty.getText(); // Get the text from your input field
        if (!qty.isEmpty()) {
            quntity = Integer.parseInt(txt_qty.getText());
        }
        String int_id = cmb_inventory.getSelectedItem().toString();
        switch (int_id){
            case "Laptop" -> invent_id = 1;
            case "Desktop" -> invent_id = 2;
            case "Phone" -> invent_id = 3;
            case "Tab" -> invent_id = 4;
            case "Tv" -> invent_id = 5;
            default -> {
            }
        }   
        
        product.edit(userId,pName,discription,price,quntity,invent_id);
        product.autoIncrement();
        txt_pId.setText(Integer.toString (product.getId()));
        tbl_product.setModel(DbUtils.resultSetToTableModel(product.populate()));
       // TODO add your handling code here:
    }//GEN-LAST:event_btn_editActionPerformed

    private void tbl_productMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_productMouseClicked
        DefaultTableModel model = (DefaultTableModel)tbl_product.getModel();
        int myIndex = tbl_product.getSelectedRow();
        txt_pId.setText(model.getValueAt(myIndex,0).toString());
        txt_pName.setText(model.getValueAt(myIndex,1).toString());
        txt_discription.setText(model.getValueAt(myIndex,2).toString());
        txt_price.setText(model.getValueAt(myIndex,3).toString());
        txt_qty.setText(model.getValueAt(myIndex,4).toString());
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_productMouseClicked

    private void btn_dltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dltActionPerformed
         int invent_id = 0;
        int userId = 0;
        
        String id = txt_pId.getText(); // Get the text from your input field
        if (!id.isEmpty()) {
            userId = Integer.parseInt(txt_pId.getText());
        }
       
        String int_id = cmb_inventory.getSelectedItem().toString();
        switch (int_id){
            case "Laptop" -> invent_id = 1;
            case "Desktop" -> invent_id = 2;
            case "Phone" -> invent_id = 3;
            case "Tab" -> invent_id = 4;
            case "Tv" -> invent_id = 5;
            default -> {
            }
        }   
        
        product.delete(userId,invent_id);
        product.autoIncrement();
        txt_pId.setText(Integer.toString (product.getId()));
        tbl_product.setModel(DbUtils.resultSetToTableModel(product.populate()));
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_dltActionPerformed

    private void txt_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_homeActionPerformed
        Home frame = new Home();
        frame.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_txt_homeActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        int a =JOptionPane.showConfirmDialog(null,"Do you really want to Exit?","Exit",JOptionPane.YES_NO_OPTION);
            if(a ==0)
            {
                System.exit(0);
            }        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Product1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Product1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Product1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Product1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Product1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_dlt;
    private javax.swing.JButton btn_edit;
    private javax.swing.JComboBox<String> cmb_inventory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_name2;
    private javax.swing.JLabel lbl_name4;
    private javax.swing.JTable tbl_product;
    private javax.swing.JTextField txt_discription;
    private javax.swing.JButton txt_home;
    private javax.swing.JTextField txt_pId;
    private javax.swing.JTextField txt_pName;
    private javax.swing.JTextField txt_price;
    private javax.swing.JTextField txt_qty;
    // End of variables declaration//GEN-END:variables
}
